runtime: python39  # Use the appropriate Python runtime version

entrypoint: gunicorn -b :$PORT app:app  # Update 'app:app' to match your Flask app's module and variable name

instance_class: F2  # Adjust the instance class as needed

env_variables:
  # Add any environment variables your app requires here, if any

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto