runtime: python311  # Use the appropriate Python runtime version

entrypoint: gunicorn -b :$PORT app:app  # Replace "app" with your Flask app's variable name

env_variables:
  # Add any environment variables your Flask app needs here
  # For example, if you have a secret key:
  SECRET_KEY: your_secret_key_here

handlers:
- url: /static
  static_dir: static  # If you have static files in a "static" directory

- url: /models
  static_dir: models  # If you have model files in a "models" directory

- url: /templates
  static_dir: templates  # If you have template files in a "templates" directory

- url: /.*
  script: auto